#:import Info tabs.info
#:import LightsAC tabs.lightsac
#:import MyTabbedPanel uix.mytabbedpanel
#:import Music tabs.music
#:import TV tabs.tv

RelativeLayout:
        MyTabbedPanel:
                do_default_tab: False
                tab_width: root.width / len(self.tab_list)
                tab_height: self.height * .1
                Music:
                TV:
                LightsAC:
                Info:
